# VeloFlux Prometheus Alert Rules

groups:
- name: veloflux.rules
  rules:
  
  # High-level service availability
  - alert: VeloFluxDown
    expr: up{job="veloflux-lb"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "VeloFlux Load Balancer is down"
      description: "VeloFlux Load Balancer instance {{ $labels.instance }} has been down for more than 1 minute."

  - alert: VeloFluxHighErrorRate
    expr: rate(veloflux_http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High error rate in VeloFlux"
      description: "VeloFlux error rate is {{ $value }} errors per second on {{ $labels.instance }}"

  # Performance alerts
  - alert: VeloFluxHighLatency
    expr: histogram_quantile(0.95, rate(veloflux_http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High latency in VeloFlux"
      description: "95th percentile latency is {{ $value }}s on {{ $labels.instance }}"

  - alert: VeloFluxHighMemoryUsage
    expr: process_resident_memory_bytes{job="veloflux-lb"} / 1024 / 1024 > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "VeloFlux high memory usage"
      description: "VeloFlux memory usage is {{ $value }}MB on {{ $labels.instance }}"

  # Backend health
  - alert: BackendDown
    expr: veloflux_backend_up == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Backend server is down"
      description: "Backend {{ $labels.backend }} in pool {{ $labels.pool }} is down"

  - alert: BackendHighResponseTime
    expr: veloflux_backend_response_time_seconds > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Backend high response time"
      description: "Backend {{ $labels.backend }} response time is {{ $value }}s"

  # System resources
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

  - alert: HighDiskUsage
    expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage"
      description: "Disk usage is {{ $value }}% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

  # Redis alerts
  - alert: RedisDown
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis instance {{ $labels.instance }} is down"

  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis high memory usage"
      description: "Redis memory usage is {{ $value }}% on {{ $labels.instance }}"

  # PostgreSQL alerts
  - alert: PostgreSQLDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL is down"
      description: "PostgreSQL instance {{ $labels.instance }} is down"

  - alert: PostgreSQLTooManyConnections
    expr: postgres_connections_active / postgres_connections_max * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL too many connections"
      description: "PostgreSQL connections usage is {{ $value }}% on {{ $labels.instance }}"

  # SSL certificate expiration
  - alert: SSLCertificateExpiringSoon
    expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate expiring soon"
      description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days"

  - alert: SSLCertificateExpired
    expr: ssl_certificate_expiry_seconds - time() < 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "SSL certificate expired"
      description: "SSL certificate for {{ $labels.domain }} has expired"

  # Rate limiting alerts
  - alert: HighRateLimitHits
    expr: rate(veloflux_rate_limit_hits_total[5m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High rate limit hits"
      description: "Rate limit hits per second: {{ $value }} on {{ $labels.instance }}"

  # WAF alerts
  - alert: HighWAFBlocks
    expr: rate(veloflux_waf_blocks_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High WAF blocks"
      description: "WAF blocks per second: {{ $value }} on {{ $labels.instance }}"

  # Cluster alerts
  - alert: ClusterNodeDown
    expr: veloflux_cluster_nodes_up < veloflux_cluster_nodes_total
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Cluster node down"
      description: "{{ $value }} cluster nodes are down"
