apiVersion: apps/v1
kind: Deployment
metadata:
  name: veloflux
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: veloflux
  template:
    metadata:
      labels:
        app: veloflux
    spec:
      securityContext:
        runAsUser: 65532
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      containers:
        - name: veloflux
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["--config=/etc/veloflux/config.yaml"]
          env:
            - name: VF_REDIS_ADDR
              value: "{{ include \"veloflux.redisAddr\" . }}"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/veloflux
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: veloflux-config
