apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veloflux
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: veloflux
                port:
                  number: {{ .Values.service.ports.http }}
