
# SkyPilot LB Configuration Example
global:
  bind_address: "0.0.0.0:80"
  tls_bind_address: "0.0.0.0:443"
  metrics_address: "0.0.0.0:8080"
  
  # TLS Configuration
  tls:
    auto_cert: true
    acme_email: "admin@example.com"
    cert_dir: "/etc/ssl/certs/skypilot"

  # Health Check Defaults
  health_check:
    interval: "30s"
    timeout: "5s"
    retries: 3

  # Rate Limiting
  rate_limit:
    requests_per_second: 100
    burst_size: 200
    cleanup_interval: "5m"

  # GeoIP Configuration
  geoip:
    enabled: false
    database_path: "/etc/geoip/GeoLite2-City.mmdb"

# Backend Pools
pools:
  - name: "web-servers"
    algorithm: "round_robin"
    sticky_sessions: true
    
    backends:
      - address: "backend-1:80"
        weight: 100
        health_check:
          path: "/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200
          
      - address: "backend-2:80"
        weight: 100
        health_check:
          path: "/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  - name: "api-servers"
    algorithm: "least_conn"
    sticky_sessions: false
    
    backends:
      - address: "api-1:8080"
        weight: 150
        health_check:
          path: "/api/health"
          
      - address: "api-2:8080"
        weight: 100
        health_check:
          path: "/api/health"

# Routing Rules
routes:
  - host: "example.com"
    pool: "web-servers"
    
  - host: "www.example.com"
    pool: "web-servers"
    
  - host: "api.example.com"
    pool: "api-servers"
    path_prefix: "/api"
