# VeloFlux Backend Configuration
# Configuração otimizada para nova estrutura: Frontend separado + Backend API

global:
  bind_address: "0.0.0.0:80"
  tls_bind_address: "0.0.0.0:443"
  metrics_address: "0.0.0.0:8080"
  
  health_check:
    interval: "30s"
    timeout: "5s"
    retries: 3

  rate_limit:
    requests_per_second: 100
    burst_size: 200
    cleanup_interval: "5m"

  waf:
    enabled: true
    level: "standard"
    log_violations: true

  geoip:
    enabled: true

  ai:
    enabled: true

# Authentication Configuration
auth:
  enabled: true
  jwt_secret: "veloflux-secure-token-change-in-production"
  jwt_issuer: "veloflux-lb"
  jwt_audience: "veloflux-admin"
  token_validity: "12h"
  oidc_enabled: false
  # OIDC Config for future use
  oidc:
    enabled: false
    issuer_url: "https://accounts.google.com"
    client_id: ""
    redirect_uri: "http://localhost/api/auth/callback"

# Clustering Configuration
cluster:
  enabled: true
  redis_address: "redis:6379"
  redis_password: ""
  redis_db: 0
  node_id: ""
  heartbeat_interval: "5s"
  leader_timeout: "15s"

# API Server Configuration - IMPORTANTE!
api:
  bind_address: "0.0.0.0:9090"
  auth_enabled: true
  username: "admin"
  password: "veloflux-admin-password"

# Multi-tenant Configuration
tenant:
  multi_tenant: true

# Backend Pools - Para o Load Balancer (porta 80)
pools:
  - name: "frontend-pool"
    algorithm: "round_robin"
    sticky_sessions: false
    backends:
      - address: "frontend:80"
        weight: 100
        health_check:
          path: "/"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

# Routing Rules - Para o Load Balancer (porta 80)
routes:
  - host: "*"
    pool: "frontend-pool"
    path_prefix: "/"

# Tenants Configuration - Para o sistema multi-tenant
tenants:
  - id: "default"
    name: "Default Tenant"
    description: "Default tenant for basic usage"
    enabled: true
    policies: ["read", "write"]
