# VeloFlux Backend Configuration
# Configuração de produção com autenticação habilitada

global:
  bind_address: "0.0.0.0:80"
  tls_bind_address: "0.0.0.0:443"
  metrics_address: "0.0.0.0:8080"
  
  health_check:
    interval: "30s"
    timeout: "5s"
    retries: 3

  rate_limit:
    requests_per_second: 100
    burst_size: 200
    cleanup_interval: "5m"

  waf:
    enabled: true
    level: "standard"
    log_violations: true

  ai:
    enabled: false

# Authentication Configuration - PRODUÇÃO ATIVA
auth:
  enabled: true
  jwt_secret: "VeloFlux2025-Production-Secret-Key-Super-Secure"
  jwt_issuer: "veloflux-production"
  jwt_audience: "veloflux-users"
  token_validity: "8h"
  refresh_token_validity: "24h"
  password_policy:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
  oidc:
    enabled: true
    issuer_url: "https://accounts.google.com"
    client_id: "your-google-client-id"
    client_secret: "your-google-client-secret"
    redirect_uri: "http://localhost/auth/callback"

# API Server Configuration - AUTENTICAÇÃO ATIVA
api:
  bind_address: "0.0.0.0:9090"
  auth_enabled: true
  username: "admin"
  password: "VeloFlux2025!"
  cors_enabled: true
  allowed_origins: ["http://localhost", "http://localhost:3000", "http://localhost:80"]
  rate_limit:
    enabled: true
    requests_per_minute: 100

# Cluster Configuration
cluster:
  enabled: true
  redis_address: "redis:6379"
  redis_password: ""
  redis_db: 0
  instance_id: "veloflux-backend"
  heartbeat_interval: "30s"
  leader_election_timeout: "60s"

# Tenant Configuration
tenant:
  enabled: true
  default_limits:
    requests_per_second: 100
    concurrent_connections: 1000
    bandwidth_mbps: 100
  auto_provisioning: true

# Billing Configuration
billing:
  enabled: true
  provider: "stripe"
  webhook_endpoint: "/billing/webhook"

# User accounts for testing
users:
  - username: "admin"
    password: "VeloFlux2025!"
    role: "admin"
    email: "admin@veloflux.io"
    
  - username: "user1"
    password: "User123!"
    role: "user"
    email: "user1@veloflux.io"
    
  - username: "tenant1"
    password: "Tenant123!"
    role: "tenant"
    email: "tenant1@veloflux.io"

# Backend Pools
pools:
  # Pool para o tenant1
  - name: "tenant1-pool"
    algorithm: "round_robin"
    sticky_sessions: true
    backends:
      - address: "backend-tenant1:80"
        weight: 100
        health_check:
          path: "/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  # Pool para o tenant2
  - name: "tenant2-pool"
    algorithm: "round_robin"
    sticky_sessions: true
    backends:
      - address: "backend-tenant2:80"
        weight: 100
        health_check:
          path: "/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  # Pool para APIs
  - name: "api-pool"
    algorithm: "least_conn"
    sticky_sessions: false
    backends:
      - address: "backend-tenant1:80"
        weight: 100
        health_check:
          path: "/api/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200
      - address: "backend-tenant2:80"
        weight: 100
        health_check:
          path: "/api/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  # Pool para área administrativa
  - name: "admin-pool"
    algorithm: "least_conn"
    sticky_sessions: true
    backends:
      - address: "backend-tenant1:80"
        weight: 100
        health_check:
          path: "/admin/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  # Pool para site público principal
  - name: "public-pool"
    algorithm: "round_robin"
    sticky_sessions: true
    backends:
      - address: "backend-tenant1:80"
        weight: 100
        health_check:
          path: "/public/health"
          interval: "15s"
          timeout: "3s"
          expected_status: 200

  # Pool para APIs internas
  - name: "internal-api"
    algorithm: "round_robin"
    sticky_sessions: false
    backends:
      - address: "localhost:9090"
        weight: 100
        health_check:
          path: "/health"
          interval: "30s"
          timeout: "5s"
          expected_status: 200

# Routing Rules
routes:
  # Rotas de domínios públicos
  - host: "public.dev.veloflux.io"
    pool: "public-pool"
    path_prefix: "/public"
    
  - host: "tenant1.public.dev.veloflux.io"
    pool: "tenant1-pool"
    path_prefix: "/"

  - host: "tenant2.public.dev.veloflux.io"
    pool: "tenant2-pool"
    path_prefix: "/"

  - host: "api.public.dev.veloflux.io"
    pool: "api-pool"
    path_prefix: "/api"

  - host: "admin.public.dev.veloflux.io"
    pool: "admin-pool"
    path_prefix: "/admin"

  # Suporte a wildcard para subdomínios
  - host: "*.public.dev.veloflux.io"
    pool: "public-pool"
    path_prefix: "/public"

  # Rotas para APIs internas
  - host: "*"
    pool: "internal-api"
    path_prefix: "/api"
