name: helm

on:
  push:
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Lint chart
        run: helm lint charts/veloflux
      - name: Package chart
        run: helm package charts/veloflux
